#pragma once


//===================================================================//
//
//
//
//===================================================================//

// ERROR ReturnCode
namespace App
{
	namespace ErrorCode
	{
		typedef enum
		{
			eRETURN_CODE_NONE					= 0,   // @param NONE
			eRETURN_CODE_NOT_FILE				= 1000,
			eRETURN_CODE_INVALID_FILE_VRAM,
			eRETURN_CODE_INVALID_VALUE,
			eRETURN_CODE_INVALID_RESOURCE,
			eRETURN_CODE_INVALID_TRANSITION,
			eRETURN_CODE_INVALID_FILEFORMAT,
			eRETURN_CODE_ENDED_PROCESS,
			eRETURN_CODE_PARAMETER_NOT_FOUND,
			eRETURN_CODE_NOT_ENOUGH_VALUE,
			eRETURN_CODE_OVER_LIMIT,
			eRETURN_CODE_CANT_ACTION,
			eRETURN_CODE_DISABLE_SYSTEM,
			eRETURN_CODE_INVALID_MATERIAL_SELECT,
			eRETURN_CODE_EQUIPMENT_EMPTY,
			eRETURN_CODE_NOT_PERMITTED,
			eRETURN_CODE_NOT_READY,
			eRETURN_CODE_NOT_FOUND,
			eRETURN_CODE_NOT_FINISH,
			eRETURN_CODE_ALREADY_EXISTS,
			eRETURN_CODE_ALREADY_DONE,
			eRETURN_CODE_ALREADY_STARTED,
			eRETURN_CODE_LOGIC_ERROR,
			eRETURN_CODE_UNCONFIRMED,

			eRETURN_CODE_DXLIB_ERROR			= 2000,
			eRETURN_CODE_DXLIB_ACCESS_END,

			eRETURN_CODE_EFFEKSEER_ERROR		= 3000,
			eRETURN_CODE_EFFEKSEER_NOTFILED,

			eRETURN_CODE_LUALIB_ERROR			= 4000,

			eRETURN_CODE_END,

		} ENUM_RESULT_ERROR_CODE;

	}/* namespace ErrorCode */
}



/* End appErrorCode.h */



